sudo: required
dist: trusty
language: node_js
node_js: 7.6
before_install:
  - npm install -g ethereumjs-testrpc@3.0.5
  - npm install -g truffle@3.4.3
  - npm i -g makeshift && makeshift -s @s083r -r registry.npmjs.org
  - rm truffle.js
  - mv truffle-cb.js truffle.js
script:
  - testrpc -g 1 --network-id 424242 > /dev/null &
  - truffle migrate --network test
  - truffle test --network test
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    truffle migrate --network kovan
    git config credential.helper "store --file=.git/credentials"
    echo "https://${GITHUB_TOKEN}:@github.com" > .git/credentials
    npm run release
    npm publish
  fi
