sudo: required
dist: trusty
language: node_js
node_js: 7
before_install:
  - 'if [ $TRAVIS_BRANCH == "develop" ]; then echo "test"; elif [ $TRAVIS_BRANCH == "release" ]; then echo "preprod"; elif [ $TRAVIS_BRANCH == "master" ]; then echo "prod";'
  - jq '.name = $BRANCH' package.json > tmp.json
  - cat tmp.json
  - rm -rf package.json 
  - mv tmp.json package.json
  - cat package.json
  - npm install -g ethereumjs-testrpc@3.0.5
  - npm install -g truffle@3.4.3
  - npm install -g mikefluff/truffle-hdwallet-provider
  - npm i -g makeshift && makeshift -s @s083r -r registry.npmjs.org
  - echo $SLACK_TOKEN > wallet.json
script:
  - testrpc -g 1 --network-id 424242 > /dev/null &
  - truffle migrate --network test
deploy:
  provider: npm
  email: $EMAIL
  api_key: $NPM_TOKEN
  skip_cleanup: true
  on:
    all_branches: true
notifications:
  slack: chrono-dev:bf19bTX1MdECbsH7a7WfU9hx

