sudo: false
dist: trusty
language: node_js
node_js: 7
before_install:
- export PATH=$PATH:$(pwd)/node_modules/.bin
- git config --global user.email "danila.zubkov@gmail.com"
- git config --global user.name "Danila Zubkov"
- npm install -g ethereumjs-testrpc@3.0.3
- npm install -g truffle@3.1.1
script:
- testrpc -g 1 --network-id 424242 > /dev/null &
- truffle migrate --network test
- travis_wait 55 truffle test --network test
deploy:
  provider: npm
  email: $EMAIL
  api_key: $NPM_TOKEN
notifications:
  slack: $SLACK_TOKEN
  
