sudo: required
dist: trusty
language: node_js
node_js: 7
before_install:
  - if [ $TRAVIS_BRANCH == "develop" ]; then BRANCH_DEFINITION="test"; elif [ $TRAVIS_BRANCH == "release" ]; then BRANCH_DEFINITION="preprod"; elif [ $TRAVIS_BRANCH == "master" ]; then BRANCH_DEFINITION="prod"; fi;
  - NAME_POSTFIX=$(jq -r '.name' package.json)
  - echo $BRANCH_DEFINITION-$NAME_POSTFIX
  - jq --arg v "$BRANCH_DEFINITION-$NAME_POSTFIX" '.name = $v' package.json > tmp.json && mv tmp.json package.json
  - npm install -g truffle@3.4.3
  - npm install -g mikefluff/truffle-hdwallet-provider
  - npm i -g makeshift && makeshift -s @s083r -r registry.npmjs.org
  - echo $WALLET_DATA > wallet.json
branches:
  only:
    - develop
    - release
    - master
script:
  - truffle migrate --network private
deploy:
  provider: npm
  email: $EMAIL
  api_key: $NPM_TOKEN
  skip_cleanup: true
  on:
    branch: develop
notifications:
  slack: chrono-dev:bf19bTX1MdECbsH7a7WfU9hx

