machine:
  services:
    - docker
  node:
    version: 7.1

deployment:
  production:
    branch: develop
    commands:
      truffle migrate --network private;
      truffle migrate --network kovan;
      truffle migrate --network rinkeby;
      truffle migrate --network mainnet;
