version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7
    working_directory: ~/repo

    steps:
      - checkout
      - run: sed -i -e 's/pwd/'$WALLET_PWD'/g' truffle-config.js
      - run: echo $WALLET_PWD
      - run: sudo npm install -g truffle@3.4.3
      - run: sudo npm install -g mikefluff/truffle-hdwallet-provider
      - run: sudo npm install
      - run: truffle migrate --network private;
