version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7
    working_directory: ~/repo
    steps:
      - checkout
      - run: sed -i -e 's/pwd/'$WALLET_PWD'/g' truffle-config.js
      - run: sudo npm config set unsafe-perm=true
      - run: sudo npm install -g truffle@3.4.3
      - run: sudo npm install -g mikefluff/truffle-hdwallet-provider
      - run: sudo npm install
      - run: echo -e "$NPM_LOGIN\n$NPM_PWD\n$NPM_EMAIL" | npm login
      - run:
          command: |
            if [[ $CIRCLE_BRANCH == "develop" ]] || [[ $CIRCLE_BRANCH == "release" ]] || [[ $CIRCLE_BRANCH == "master" ]] ; then 
              echo "Migrate to Private"
              #truffle migrate --network private;
            fi;
      - run:
          command: |
            if [ $CIRCLE_BRANCH == "release" ] || [ $CIRCLE_BRANCH == "master" ]; then 
              echo "Migrate to Kovan"
              #truffle migrate --network kovan;
            fi;
      - run:
          command: |
            if [ $CIRCLE_BRANCH == "release" ] || [ $CIRCLE_BRANCH == "master" ]; then 
              echo "Migrate to Rinkeby"
              #truffle migrate --network rinkeby;
            fi;
      - run:
          command: |
            if [[ "$CIRCLE_BRANCH" == "master" ]]; then 
              echo "Migrate to Mainnet"
              #truffle migrate --network mainnet;
            fi;
      - run: jq --arg v "$CIRCLE_BRANCH-$(jq -r '.name' package.json)" '.name = $v' package.json > tmp.json && mv tmp.json package.json
      - run: cat package.json
      - run: npm publish
